name: "checkout"
description: "checkout sources."
inputs:
  fetch-depth:
    description: "Number of commits to fetch. 0 indicates all history for all branches and tags."
    required: false
    default: "1"

runs:
  using: "composite"
  steps:
    - name: Checkout sources
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: ${{ inputs.fetch-depth }}
        ref: |
          ${{
            github.event_name == 'pull_request_target' &&
            github.event.pull_request.head.repo.fork &&
            format('refs/pull/{0}/merge', github.event.number) ||
            ''
          }}
