name: arc-v2

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  pull_request:

jobs:
  echo-test:
    strategy:
      fail-fast: false
      matrix:
        runner: [infrastructure, centreon-common, centeon-ubuntu-22.04, centreon-collect, centreon-collect-arm64]
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: test bash
        run: |
          echo "test ok"
          echo "::notice::test notice bash"
        shell: bash

      - name: test js
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            await exec.exec("sleep 3s");
            console.log("test js");
            core.notice("test notice js");

  test-infra:
    runs-on: infrastructure
    steps:
      - name: Checkout sources
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup awscli
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          sudo unzip -q awscliv2.zip
          sudo ./aws/install
        shell: bash

      - name: test s3
        run: |
          echo "datetime=$(date '+%Y-%m-%d %H:%M %Z')" >> $GITHUB_ENV

          export $(printf "AWS_ACCESS_KEY_ID=%s AWS_SECRET_ACCESS_KEY=%s AWS_SESSION_TOKEN=%s" \
          $(aws sts assume-role \
          --role-arn ${{ secrets.CLOUDFRONT_ROLE_DOC_PRODUCTION }} \
          --role-session-name InvalidDocCache \
          --query "Credentials.[AccessKeyId,SecretAccessKey,SessionToken]" \
          --output text))

          aws s3 ls s3://centreon-documentation-preview-pr/previews/
          aws s3 ls s3://centreon-documentation-archive/

          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_ID_DOC_PREVIEW }} --paths "/previews/pr-${{ github.event.pull_request.number }}/staging/*"
        shell: bash

      - name: test ssh
        run: |
          # Prepare ssh-key
          eval `ssh-agent`
          ssh-add - <<< "${{ secrets.INT_SSH_KEY }}"

          ssh -o StrictHostKeyChecking=no admin@docs-dev.int.centreon.com ls /var/www/html
          ssh -o StrictHostKeyChecking=no admin@docs.int.centreon.co ls /var/www/
          ssh -o StrictHostKeyChecking=no admin@${{ secrets.DOC_PROD_IP_ADDRESS }} ls /var/www/
        shell: bash
