name: archive

on:
  workflow_dispatch:
  pull_request: # to delete

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: [self-hosted, infra]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup awscli
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          sudo unzip -q awscliv2.zip
          sudo ./aws/install
        shell: bash

      - name: Copy to S3
        run: |
          #aws s3 cp --recursive "build/" s3://centreon-documentation-archive/22.04/
          aws s3 sync --delete "src/*" s3://centreon-documentation-archive/22.04/

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install

      - name: Build documentation for 22.04
        run: VERSION="22.04" yarn build

      - name: Copy to S3
        run: |
          aws s3 cp --recursive "build/" s3://centreon-documentation-archive/22.04/
          #aws s3 sync --delete build s3://centreon-documentation-archive/22.04/
