name: archive

on:
  workflow_dispatch:
    # inputs:
    #   version:
    #     required: true
  pull_request: # to delete

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        version: ["20.04", "20.10", "21.04"]
    runs-on: [self-hosted, infra]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup awscli
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          sudo unzip -q awscliv2.zip
          sudo ./aws/install
        shell: bash

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install

      - name: Build documentation for ${{ matrix.version }}
        run: VERSION="${{ matrix.version }}" yarn build

      - name: Copy to S3
        run: aws s3 sync --delete "build/" s3://centreon-documentation-archive/${{ matrix.version }}/
