name: archive

on:
  workflow_dispatch:
    inputs:
      version:
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
        with:
          version: 9
          run_install: false

      - name: Set up Node
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version: 22
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        shell: bash

      - name: Redirect pp and cloud links to last documentation
        run: |
          find versioned_docs versioned_sidebars -regex ".*\.\(md\|json\)" | xargs --delimiter='\n' sed -i 's#/cloud/#https://docs.centreon.com/cloud/#g'
          find versioned_docs versioned_sidebars -regex ".*\.\(md\|json\)" | xargs --delimiter='\n' sed -i 's#/pp/#https://docs.centreon.com/pp/#g'
        shell: bash

      - name: Build documentation for ${{ github.event.inputs.version }}
        run: ARCHIVED_VERSION="${{ github.event.inputs.version }}" pnpm build

      - name: Store build archived doc in cache
        uses: actions/cache/save@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4.1.2
        with:
          path: "./build"
          key: "${{ github.sha }}-${{ github.run_id }}-build-archived-doc"

  publish:
    needs: [build]
    runs-on: [self-hosted, infra]
    steps:
      - name: Restore built archived doc from cache
        uses: actions/cache/restore@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4.1.2
        with:
          path: "./build"
          key: "${{ github.sha }}-${{ github.run_id }}-build-archived-doc"
          fail-on-cache-miss: true

      - name: Setup awscli
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          sudo unzip -q awscliv2.zip
          sudo ./aws/install
        shell: bash

      - name: Copy to S3
        run: aws s3 sync --delete "build/" s3://centreon-documentation-archive/${{ github.event.inputs.version }}/
