name: clean-previews

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - run: |
          du -sh pr-preview
          #du -sh pr-preview/*

      - run: |
          #sudo apt update
          #sudo apt install -y gifsicle
          #for file in $(find ./pr-preview -type f -name '*.gif' -not -path 'node_modules' -printf '%s %p\n' | sort -nr | cut -d ' ' -f 2); do
          #  gifsicle -O3 --colors=16 --scale=0.5 $file -o $file
          #done

          find ./pr-preview -iname \*.gif -exec sh -c "> {}" +
          find ./pr-preview -iname \*.png -exec sh -c "> {}" +
          find ./pr-preview -iname \*.jpg -exec sh -c "> {}" +

          find ./pr-preview -iname \*.pdf -exec sh -c "> {}" +
          find ./pr-preview -iname \*.xlsx -exec sh -c "> {}" +

          #sudo npm i -g @funboxteam/optimizt
          #find ./pr-preview -iname \*.png -exec optimizt {} +
          #find ./pr-preview -iname \*.jpg -exec optimizt {} +

      # - name: Compress Images
      #   if: ${{ github.event_name == 'pull_request' }}
      #   uses: calibreapp/image-actions@main
      #   with:
      #     compressOnly: true
      #     jpegQuality: '50'
      #     jpegProgressive: false
      #     pngQuality: '50'
      #     webpQuality: '50'
      #     githubToken: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          du -sh pr-preview
          #du -sh pr-preview/*
